from __future__ import annotations

import os
import sys
from pathlib import Path

import pandas as pd
import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from dashboard import db
from dashboard.discovery import discover_agents

st.set_page_config(page_title="Settings — Career Copilot", page_icon="⚙️", layout="wide")
db.init_db()

st.title("⚙️ Settings")

st.subheader("API status")
has_key = bool(os.environ.get("ANTHROPIC_API_KEY"))
st.write("✅ `ANTHROPIC_API_KEY` is set — Live mode available." if has_key else "⚠️ `ANTHROPIC_API_KEY` is not set — only Demo mode will work.")

st.subheader("Database")
st.write(f"Dashboard DB: `{db.DEFAULT_DB_PATH}`")
st.write(f"Pipeline run log: `career_copilot_runs.sqlite3`")

col1, col2 = st.columns(2)
with col1:
    if st.button("Export applications CSV"):
        path = db.export_table_csv("applications", "dashboard/applications_export.csv")
        st.success(f"Exported to `{path}`")
with col2:
    if st.button("Export applications Excel"):
        path = db.export_table_excel("applications", "dashboard/applications_export.xlsx")
        st.success(f"Exported to `{path}`")

st.divider()
st.subheader("Discovered agents")
st.caption(
    "This list is generated by scanning `career_copilot/agents/*.py` — nothing here is hardcoded. "
    "Add, remove, or modify an agent module and click Rescan to see the change reflected."
)
if st.button("🔄 Rescan agents"):
    st.cache_data.clear()

agents = discover_agents()
st.write(f"**{len(agents)} agents discovered.**")

df = pd.DataFrame([{
    "id": a.id, "name": a.display_name, "category": a.category,
    "requires": ", ".join(a.requires), "depends_on": ", ".join(a.depends_on) or "—",
    "inputs": len(a.input_fields), "outputs": len(a.output_fields),
} for a in agents])
st.dataframe(df, use_container_width=True, hide_index=True)

for a in agents:
    with st.expander(f"{a.display_name} (`{a.id}`)"):
        st.write(a.description)
        st.write(f"**Category:** {a.category}")
        st.write(f"**Depends on:** {', '.join(a.depends_on) or 'none'}")
        st.write("**Input fields:**")
        st.table(pd.DataFrame([{"field": f.name, "type": f.type, "required": f.required} for f in a.input_fields]))
        st.write("**Output fields:**")
        st.table(pd.DataFrame([{"field": f.name, "type": f.type} for f in a.output_fields]))
